language: java

jdk:
- openjdk8

# Send coverage data to Coveralls
deploy:
  provider: script
  script: mvn coveralls:report -DrepoToken=$COVERALLS_REPO_TOKEN
  on:
    branch: master

notifications:
  email: false
